### ISSUE TITLE
Link overflow on 1280*800 resolution

### ISSUE THREAD

**Issue by bingluen** [sitcon-tw/2017#33]
1280 * 800 解析度會因為增加了「個人贊助」的 Link 導致 Overflow
(MacBook Retina viewport 會是螢幕解析度邊長都除二)

![](http://imgur.com/download/SJyqffS)

**Comment by denny0223** [comment]
#45 有處理了 效果 OK 嗎?

**Comment by bingluen** [comment]
看起來是沒問題了

但是 #45 嗎..

是 #43  吧？

**Comment by coin3x** [comment]
對 是 #43
