### ISSUE TITLE
接駁車資訊

### ISSUE THREAD

**Issue by bingluen** [sitcon-tw/2017#41]
交通資訊頁面是否要增加年會當日早上接駁車相關資訊？

**Comment by sunset1995** [comment]
好～  相信會幫助第一次來的很多
請問你有相關資訊嗎？
沒有的話我丟信問問

**Comment by bingluen** [comment]
我印象中在寫行前信的時候是 8:00- 10:00 在南港展覽館二號出口會有工作人員引導

**Comment by denny0223** [comment]
#42 已經補上囉~
